// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.quickstart.server.memcache;

import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.annotation.*;
import com.qq.tars.common.support.Holder;

@Servant
public interface MemCacheIServant {

	 int get(@TarsMethodParameter(name="k")Request k, @TarsHolder(name="v") Holder<Reponse> v);

	 int set(@TarsMethodParameter(name="k")Request k, @TarsMethodParameter(name="v")Reponse v);
}
