// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.quickstart.server.memcache;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Reponse {

	@TarsStructProperty(order = 0, isRequire = true)
	public String message = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String responseCode = "";

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getResponseCode() {
		return responseCode;
	}

	public void setResponseCode(String responseCode) {
		this.responseCode = responseCode;
	}

	public Reponse() {
	}

	public Reponse(String message, String responseCode) {
		this.message = message;
		this.responseCode = responseCode;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(message);
		result = prime * result + TarsUtil.hashCode(responseCode);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Reponse)) {
			return false;
		}
		Reponse other = (Reponse) obj;
		return (
			TarsUtil.equals(message, other.message) &&
			TarsUtil.equals(responseCode, other.responseCode) 
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Reponse(");
		sb.append("message:");
		if (this.message == null) {
			sb.append("null");
		} else {
			sb.append(this.message);
		}
		sb.append(", ");
		sb.append("responseCode:");
		if (this.responseCode == null) {
			sb.append("null");
		} else {
			sb.append(this.responseCode);
		}
		sb.append(")");
		return sb.toString();
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(message, 0);
		_os.write(responseCode, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.message = _is.readString(0, true);
		this.responseCode = _is.readString(1, true);
	}

}
