// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.quickstart.server.memcache;

import com.qq.tars.protocol.util.*;
import com.qq.tars.protocol.annotation.*;
import com.qq.tars.protocol.tars.*;
import com.qq.tars.protocol.tars.annotation.*;

@TarsStruct
public class Request {

	@TarsStructProperty(order = 0, isRequire = true)
	public String message = "";
	@TarsStructProperty(order = 1, isRequire = true)
	public String requestId = "";

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getRequestId() {
		return requestId;
	}

	public void setRequestId(String requestId) {
		this.requestId = requestId;
	}

	public Request() {
	}

	public Request(String message, String requestId) {
		this.message = message;
		this.requestId = requestId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + TarsUtil.hashCode(message);
		result = prime * result + TarsUtil.hashCode(requestId);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Request)) {
			return false;
		}
		Request other = (Request) obj;
		return (
			TarsUtil.equals(message, other.message) &&
			TarsUtil.equals(requestId, other.requestId) 
		);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Request(");
		sb.append("message:");
		if (this.message == null) {
			sb.append("null");
		} else {
			sb.append(this.message);
		}
		sb.append(", ");
		sb.append("requestId:");
		if (this.requestId == null) {
			sb.append("null");
		} else {
			sb.append(this.requestId);
		}
		sb.append(")");
		return sb.toString();
	}

	public void writeTo(TarsOutputStream _os) {
		_os.write(message, 0);
		_os.write(requestId, 1);
	}


	public void readFrom(TarsInputStream _is) {
		this.message = _is.readString(0, true);
		this.requestId = _is.readString(1, true);
	}

}
