// **********************************************************************
// This file was generated by a TARS parser!
// TARS version 1.7.2.
// **********************************************************************

package com.qq.tars.quickstart.client.testapp;

import com.qq.tars.rpc.protocol.tars.support.TarsAbstractCallback;

public abstract class HelloPrxCallback extends TarsAbstractCallback {

	public abstract void callback_test(int ret);

	public abstract void callback_testHello(int ret, String sRsp);

}
